# Generated by Django 4.2 on 2023-05-04 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'Ya este teléfono está registrado'}, help_text='Poner el código del país', max_length=15, null=True, unique=True, verbose_name='Teléfono')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Link de Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Link de Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Link de Twitter')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Link de Whatsapp')),
                ('logo', models.ImageField(upload_to='config/logo/', verbose_name='Logo')),
                ('icon', models.ImageField(upload_to='config/icon/', verbose_name='Ícono')),
                ('banner', models.ImageField(upload_to='config/banner/', verbose_name='Banner')),
                ('footer', models.ImageField(upload_to='config/footer/', verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre y apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('phone_number', models.CharField(blank=True, help_text='Poner el código del país', max_length=15, null=True, verbose_name='Teléfono')),
                ('is_attended', models.BooleanField(default=False, verbose_name='Está atendido')),
            ],
            options={
                'verbose_name': 'Contacto',
                'ordering': ['is_attended'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('1', 'Enviada'), ('2', 'No enviada')], default='2', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Oferta',
                'ordering': ('status', 'date_created'),
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('link_de_pago', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.FloatField(default=0, verbose_name='Importe total')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Completada'), ('3', 'Cancelada')], default='2', max_length=10, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('address', models.CharField(max_length=900, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ('-date_created', '-status'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/img', verbose_name='Imagen')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Información')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('is_important', models.BooleanField(default=False, verbose_name='Destacado')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='Ventas')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Subscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'verbose_name_plural': 'Subscriptores',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, verbose_name='Característica')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='ComponenteOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respaldo', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componente_orden', to='app_main.orden')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componente_producto', to='app_main.product')),
            ],
            options={
                'verbose_name': 'Componente de venta',
                'verbose_name_plural': 'Componentes de ventas',
                'ordering': ('orden', 'producto'),
            },
        ),
    ]
