# Generated by Django 4.2 on 2023-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'Ya este teléfono está registrado'}, help_text='Poner el código del país', max_length=15, null=True, unique=True, verbose_name='Teléfono')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Link de Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Link de Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Link de Twitter')),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Whatsapp')),
                ('logo', models.ImageField(upload_to='config/logo/', verbose_name='Logo')),
                ('icon', models.ImageField(upload_to='config/icon/', verbose_name='Ícono')),
                ('banner', models.ImageField(upload_to='config/banner/', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
