# Generated by Django 4.2 on 2023-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_product_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
