# Generated by Django 4.2 on 2023-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_product_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre y apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_attended', models.BooleanField(default=False, verbose_name='Está atendido')),
            ],
            options={
                'verbose_name': 'Contacto',
                'ordering': ['is_attended'],
            },
        ),
    ]
