# Generated by Django 4.2 on 2023-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Poner el código del país', max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
