# Generated by Django 4.2 on 2023-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'verbose_name_plural': 'Subscriptores',
            },
        ),
    ]
