# Generated by Django 4.2 on 2023-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_orden_product_sales_componenteorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Oferta',
                'ordering': ('date_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='componenteorden',
            options={'ordering': ('orden', 'producto'), 'verbose_name': 'Componente de venta', 'verbose_name_plural': 'Componentes de ventas'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ('-date_created', '-status'), 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('1', 'Completada'), ('3', 'Cancelada')], default='2', max_length=10, verbose_name='Estado'),
        ),
    ]
