# Generated by Django 4.2 on 2023-04-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_offer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('status', 'date_created'), 'verbose_name': 'Oferta'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='config',
            name='footer',
            field=models.ImageField(default='asd', upload_to='config/footer/', verbose_name='Footer'),
            preserve_default=False,
        ),
    ]
